name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev

      - name: Install dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install boost

      - name: Configure with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DPATCH_VERSION=${{ github.run_number }}

      - name: Build the project
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Create package
        run: |
          cd build
          cpack

      - name: Verify artifacts
        run: |
          echo "Listing files in the build directory:"
          ls -la ./build

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify artifacts
        run: |
          echo "Verifying build directory contents:"
          ls -la ./build

      - name: Create release using gh cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "release-${{ github.run_number }}" \
            ./build/helloworld-0.0.${{ github.run_number }}-Linux.deb \
            ./build/helloworld-0.0.${{ github.run_number }}-Darwin.dmg \
            --title "Release ${{ github.run_number }}" \
            --notes "Automated release by GitHub Actions"
