name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev

      - name: Install dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install boost

      - name: Configure with CMake
        run: |
          cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build the project
        run: |
          cmake --build .

      - name: Run tests
        run: |
          cmake --build . --target test

      - name: Create package
        run: |
          cmake --build . --target package

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release using gh cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "release-${{ github.run_number }}" ./helloworld-0.0.${{ github.run_number }}-Linux.deb ./helloworld-0.0.${{ github.run_number }}-Darwin.dmg \
            --title "Release ${{ github.run_number }}" \
            --notes "Automated release by GitHub Actions"

      - name: Verify release
        run: |
          gh release view "release-${{ github.run_number }}"